[net] uapi: fix linux/rxrpc.h userspace compilation errors
Message-id: <20180110160622.26131-2-yselkowi@redhat.com>
Patchwork-id: 203509
O-Subject: [RHEL-ALT-7.5 PATCH 1/3] uapi: fix linux/rxrpc.h userspace compilation errors
Bugzilla: 1510150
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1510150
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=14909037
Tested: Compiled a file with #include <linux/rxrpc.h>
Upstream Status: merged into 4.15 and 4.14.3

commit 0eef304bc9f7d079a1165e8cd2f24b078e9e1f2a
Author: Dmitry V. Levin <ldv@altlinux.org>
Date:   Mon, 13 Nov 2017 03:37:06 +0300

    Consistently use types provided by <linux/types.h> to fix the following
    linux/rxrpc.h userspace compilation errors:

    /usr/include/linux/rxrpc.h:24:2: error: unknown type name 'u16'
      u16  srx_service; /* service desired */
    /usr/include/linux/rxrpc.h:25:2: error: unknown type name 'u16'
      u16  transport_type; /* type of transport socket (SOCK_DGRAM) */
    /usr/include/linux/rxrpc.h:26:2: error: unknown type name 'u16'
      u16  transport_len; /* length of transport address */

    Use __kernel_sa_family_t instead of sa_family_t the same way
    as uapi/linux/in.h does, to fix the following
    linux/rxrpc.h userspace compilation errors:

    /usr/include/linux/rxrpc.h:23:2: error: unknown type name 'sa_family_t'
      sa_family_t srx_family; /* address family */
    /usr/include/linux/rxrpc.h:28:3: error: unknown type name 'sa_family_t'
      sa_family_t family;  /* transport address family */

    Fixes: 727f8914477e ("rxrpc: Expose UAPI definitions to userspace")
    Signed-off-by: Dmitry V. Levin <ldv@altlinux.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>