[net] uapi: fix linux/tls.h userspace compilation error
Message-id: <20180110160622.26131-3-yselkowi@redhat.com>
Patchwork-id: 203511
O-Subject: [RHEL-ALT-7.5 PATCH 2/3] uapi: fix linux/tls.h userspace compilation error
Bugzilla: 1510150
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1510150
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=14909037
Tested: Compiled a file with #include <linux/tls.h>
Upstream Status: merged into 4.15 and 4.14.3

commit b9f3eb499d84f8d4adcb2f9212ec655700b28228
Author: Dmitry V. Levin <ldv@altlinux.org>
Date:   Tue, 14 Nov 2017 06:30:11 +0300

    uapi: fix linux/tls.h userspace compilation error

    Move inclusion of a private kernel header <net/tcp.h>
    from uapi/linux/tls.h to its only user - net/tls.h,
    to fix the following linux/tls.h userspace compilation error:

    /usr/include/linux/tls.h:41:21: fatal error: net/tcp.h: No such file or directory

    As to this point uapi/linux/tls.h was totaly unusuable for userspace,
    cleanup this header file further by moving other redundant includes
    to net/tls.h.

    Fixes: 3c4d7559159b ("tls: kernel TLS support")
    Signed-off-by: Dmitry V. Levin <ldv@altlinux.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>