[redhat] fix-up modules signing
Build is still breaking with

 > + mv certs/signing_key.pem.sign.debug signing_key.pem
 > mv: cannot stat 'certs/signing_key.pem.sign.debug': No such file or directory
 > error: Bad exit status from /var/tmp/rpm-tmp.SPMuAC (%install)
 >    Bad exit status from /var/tmp/rpm-tmp.SPMuAC (%install)

This patch partially reverts "753db92 [redhat] spec: adjust build
recipes for the new kernel infrastructure" to get rid of hunks
where I unwittingly forced 'certs/' as a prefix for the dumped
signed certificate.

We also change redhat/scripts/sign-modules so it picks the proper
private certificate, which is now named signing_key.pem

Signed-off-by: Rafael Aquini <aquini@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>