[drm] uapi: fix linux/kfd_ioctl.h userspace compilation errors
Message-id: <20180110160622.26131-4-yselkowi@redhat.com>
Patchwork-id: 203508
O-Subject: [RHEL-ALT-7.5 PATCH 3/3] uapi: fix linux/kfd_ioctl.h userspace compilation errors
Bugzilla: 1510150
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1510150
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=14909037
Tested: Compiled a file with #include <linux/kfd_ioctl.h>
Upstream Status: merged in 4.15

commit b4d085201d86af69cbda2214c6dafc0be240ef9f
Author: Dmitry V. Levin <ldv@altlinux.org>
Date:   Mon, 13 Nov 2017 03:35:27 +0300

    Consistently use types provided by <linux/types.h> via <drm/drm.h>
    to fix the following linux/kfd_ioctl.h userspace compilation errors:

    /usr/include/linux/kfd_ioctl.h:236:2: error: unknown type name 'uint64_t'
      uint64_t va_addr; /* to KFD */
    /usr/include/linux/kfd_ioctl.h:237:2: error: unknown type name 'uint32_t'
      uint32_t gpu_id; /* to KFD */
    /usr/include/linux/kfd_ioctl.h:238:2: error: unknown type name 'uint32_t'
      uint32_t pad;
    /usr/include/linux/kfd_ioctl.h:243:2: error: unknown type name 'uint64_t'
      uint64_t tile_config_ptr;
    /usr/include/linux/kfd_ioctl.h:245:2: error: unknown type name 'uint64_t'
      uint64_t macro_tile_config_ptr;
    /usr/include/linux/kfd_ioctl.h:249:2: error: unknown type name 'uint32_t'
      uint32_t num_tile_configs;
    /usr/include/linux/kfd_ioctl.h:253:2: error: unknown type name 'uint32_t'
      uint32_t num_macro_tile_configs;
    /usr/include/linux/kfd_ioctl.h:255:2: error: unknown type name 'uint32_t'
      uint32_t gpu_id;  /* to KFD */
    /usr/include/linux/kfd_ioctl.h:256:2: error: unknown type name 'uint32_t'
      uint32_t gb_addr_config; /* from KFD */
    /usr/include/linux/kfd_ioctl.h:257:2: error: unknown type name 'uint32_t'
      uint32_t num_banks;  /* from KFD */
    /usr/include/linux/kfd_ioctl.h:258:2: error: unknown type name 'uint32_t'
      uint32_t num_ranks;  /* from KFD */

    Fixes: 6a1c9510694fe ("drm/amdkfd: Adding new IOCTL for scratch memory v2")
    Fixes: 5d71dbc3a5886 ("drm/amdkfd: Implement image tiling mode support v2")
    Signed-off-by: Dmitry V. Levin <ldv@altlinux.org>
    Signed-off-by: Oded Gabbay <oded.gabbay@gmail.com>

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>